### ISSUE TITLE
Package not working together with other resource-table alternating packages.

### ISSUE THREAD

**Issue by cord** [optimistdigital/nova-resizable#1]
What needs to be done to enable the resizable feature? Just installing the package seems not to work? However I can see the js and css resources are loaded.

**Comment by KasparRosin** [comment]
Just installing the package should be enough. 

I released 1.0.1 that included some styling fixes that might have prevented it from working properly before.

**Comment by cord** [comment]
thanks for checking, updated to the latest release but still no luck. I can see the resources are loaded, but the frontend does not change (no d&d handles). the console does not show any error.

**Comment by philipbaginski** [comment]
The same with me. Installed. Nothing happened. Last version of Nova. Any help?

**Comment by KasparRosin** [comment]
Interesting. I'll try to setup a nova project from scratch later today and see if i can reproduce. 
In the meantime, do you mind checking whether the `<table>` tag in your html has `resizable-resource-table` class. I wonder whether it's a problem with javascript or the vue component.

**Comment by cord** [comment]
source view of resource table:

![Browse Responses | XOmerge by Act in Fact Aps 2021-01-14 10-26-07](https://user-images.githubusercontent.com/158588/104571040-f0ab5780-5652-11eb-8339-9e4af8a7f7e8.png)

**Comment by KasparRosin** [comment]
Do you have any other packages that are overriding the resource-table component?

**Comment by cord** [comment]
searched `/vendor` for `nova-resource-table` but your code is the only showing up. How can I check?

**Comment by KasparRosin** [comment]
nova-resource-table is the name that i assigned it, could you search for `Vue.component('resource-table',`

**Comment by cord** [comment]
found this package ;)

https://github.com/optimistdigital/nova-sortable

**Comment by philipbaginski** [comment]
I uninstalled https://github.com/optimistdigital/nova-sortable and it works. Any idea how to make both packeages working together?

**Comment by philipbaginski** [comment]
One question more: normally I have no borders in the table header. With this package I have got vertical borders in the header. Is it how should be?

**Comment by KasparRosin** [comment]
@philipbaginski Yes, they are there to help you resize the columns. It makes it easier to find the spots where you can drag to make it larger/smaller

@cord @philipbaginski Still working on the fix to get both packages working together.

**Comment by KasparRosin** [comment]
Update:
I didn't find any good/workable fixes for issue that i could build inside this package. Seems quite impossible currently.

In the meanwhile, i created a discussion #2 on how to work around this in your project. 

I will close this issue, and we can carry over this conversation to #2 where if anybody has other solutions for this issue can comment.
